<?php
if (1) {
?>
  <form method="get">
    <input name='query' placeholder="Product Name" \>
    <button type="submit" name='submit' value="Submit">Search</button>
    <button type="submit" name='submit' value="all">All</button>
  </form>
  <h2 class='container text-center mt-4'><?php echo ("All Products"); ?></h2>

  <?php if (isset($msg)) {
    echo $msg;
  }; ?>
  <!------------------------------------------------------------- Products Table ---------------------------------------------------->

  <table class="table table-bordered table-hover container mt-5">
    <thead class="thead-light">
      <tr>
        <th><?php echo ("Id"); ?></th>
        <th><?php echo ("Name"); ?></th>
        <th><?php echo ("Description"); ?></th>
        <th><?php echo ("Tags"); ?></th>
        <th><?php echo ("Price"); ?></th>
        <th><?php echo ("Stocks"); ?></th>
        <th><?php echo ("Operations"); ?></th>
        <th><?php echo ("Quick View"); ?></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td colspan="3"><?php echo ("Products quantity"); ?>: <?php ?></td>
      </tr>
    </tfoot>
    <tbody>
      <?php foreach ($products as $product) { ?>
        <tr>
          <td><?php echo $product->_id; ?></td>
          <td><?php echo $product->product_name; ?></td>
          <td><?php echo $product->description; ?></td>
          <td><?php echo $product->tags; ?></td>
          <td><?php echo $product->price; ?></td>
          <td><?php echo $product->stocks; ?></td>
          <td><?php echo $this->tag->linkTo(['/webhook/product/editProduct?id=' . $product->_id, ("Edit"), 'class' => 'btn btn-primary']) ?>

            <?php echo $this->tag->linkTo(['/webhook/product/delete?id=' . $product->_id, ("Delete"), 'class' => 'btn btn-danger']) ?></td>
          <td>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#<?php echo $product->_id; ?>">
              Quick View
            </button>
            <div class="modal fade" id="<?php echo $product->_id; ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">

                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Additional</h5>
                  </div>
                  <div class="modal-body">
                    <?php foreach ($product->additional as $key => $value) {

                      echo "<div class='row mx-5'> $key : $value</div>";
                    }
                    ?>
                  </div>


                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Variations</h5>

                  </div>
                  <div class="modal-body">
                    <?php foreach ($product->variation as $key => $value) {

                      echo "<div class='row mx-5'> $key :";
                      foreach ($value as $label => $data) {
                        echo " <br> <div class='mx-5'>$label : $data</div>";
                      }
                      echo "</div>";
                    }
                    ?>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

          </td>
        </tr>
      <?php } ?>
    </tbody>
  </table>
  <!------------------------------------------------------------- Products Table ---------------------------------------------------->

<?php
}
?>
