<?php
?>

<h2 class='container text-center mt-4'><?php echo ("All Orders"); ?></h2>

<!------------------------------------------------------------- Orders Table ---------------------------------------------------->

<table class="table table-bordered table-hover small container mt-5">
    <thead class="thead-light">
        <tr>

            <th><?php echo ("Products Id"); ?></th>
            <th><?php echo ("Order Date"); ?></th>
            <th><?php echo ("Customer Name"); ?></th>
            <th><?php echo ("Customer Address"); ?></th>
            <th><?php echo ("Zipcode"); ?></th>

            <th><?php echo ("Quantity"); ?></th>



        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3"><?php echo ("Order quantity"); ?>: <?php ?></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($orders as $order) {
        ?>
            <tr>

                <td><?php echo $order->product; ?></td>
                <td><?php echo $order->created_date; ?></td>
                <td><?php echo $order->customer_name; ?></td>
                <td><?php echo $order->customer_address; ?></td>
                <td><?php echo $order->zipcode; ?></td>
                <td><?php echo $order->quantity; ?></td>



            </tr>
        <?php } ?>
    </tbody>
</table>
<!------------------------------------------------------------- Orders Table ends ---------------------------------------------------->

<?php

?>