<h2>Sign up using this form</h2>

<?php echo $this->tag->form(""); ?>
<p>
    <label for="role">Role</label>
    <?php echo $this->tag->textField("role"); ?>
</p>

<p>
    <label for="username">Username</label>
    <?php echo $this->tag->textField("username"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
    <label for="password">password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>

<?php if (isset($response)) {
    print_r($response);
} ?>